[tool.pylint]
disable = [
    "C0114",  # Missing module docstring
    "C0116",  # Missing function or method docstring
]

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

default_section = "THIRDPARTY"

[tool.sort_requirements]
alphabetical = true
line_length = 80
not_sorted_sections = ["# Constants", "# Imports"]

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
